version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/clojure:lein-2.8.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: reagent-{{ checksum "project.clj" }}
      - restore_cache:
          key: reagent-npm-{{ checksum "package.json" }}
      - run: lein deps
      - run: sudo npm install -g karma-cli
      - run: ./prepare-tests.sh
      - run: ./run-tests.sh
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
            - ~/.cljs/.aot_cache
          key: reagent-{{ checksum "project.clj" }}
      - save_cache:
          paths:
            - node_modules
          key: reagent-npm-{{ checksum "package.json" }}

    environment:
      NPM_CONFIG_LOGLEVEL: warn
  deploy_master:
    working_directory: ~/work
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - add_ssh_keys
      - deploy:
          command: ./build-example-site.sh

